#FSR Autogenerated Content. DO NOT DELETE
from .get_issues import get_issues
from .get_inventory_assets import get_inventory_assets
from .get_issues_by_asset import get_issues_by_asset
from .get_projects import get_projects
from .add_comment_to_issue import add_comment_to_issue
 
supported_operations = {'get_issues': get_issues, 'get_inventory_assets': get_inventory_assets, 'get_issues_by_asset': get_issues_by_asset, 'get_projects': get_projects, 'add_comment_to_issue': add_comment_to_issue, }